modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/percivalalb/DoggyTalents/issues"
displayURL="https://minecraft.curseforge.com/projects/doggy-talents/"
logoFile="dt_logo.png"
[[mods]] #mandatory
    modId="doggytalents"
    version="${file.jarVersion}"
    updateJSONURL="https://raw.githubusercontent.com/percivalalb/DoggyTalents/1.14.x/version.json"
    displayName="Doggy Talents"
    credits="percivalalb,RaustBlackDragon,NovaViper"
    authors="percivalalb"
    description='''
    Turning your wolves into fun, playful dogs.
    '''
[[dependencies.doggytalents]] #optional
    modId="forge"
    mandatory=true
    versionRange="[28.1.0,)" #mandatory
    ordering="NONE"
    side="BOTH"